### ISSUE TITLE
コンテナ起動後の3回ほどのシミュレーションは回避動作を行わなくなる問題について

### ISSUE THREAD

**Issue by makotoyoshigoe** [AutomotiveAIChallenge/aichallenge2023-sim#31]
**発生している問題**
ローカル環境において, コンテナ起動後にシミュレーションを開始すると, 車両が課題3-1の区間にある最初のダンボールを回避せずにそのまま直進し, ダンボールに衝突してしまうという問題が起きています. この挙動は同じコンテナで3回ほどシミュレーションをやり直すとなくなり, その後はダンボールを回避するようになります. 恐らく, オンライン環境においても同様の問題が発生しており, ローカルでの点数に比べてオンラインでの点数がかなり低くなっている状態です. 対処法や解決策などあれば教えて頂きたいです. よろしくお願い致します.  

**環境**
- OS: Ubuntu 22.04.2 LTS
- CPU: AMD Ryzen 7 5800X 8-Core Processor(8 cores)
- GPU: NVIDIA Geforce RTX 3090(VRAM 24 GB)
- RAM: 64GB
- ROM: SSD 2.0TB
- ROS2: Humble

**実行コマンド**
コンテナ内の`/aichallenge`で
1. `bash build.sh`
2. `bash run.sh`

**Comment by norikenpi** [comment]
centerpointのtopicの起動に時間がかかる可能性あるかもしれないので，aichallenge_subimit.launch.xmlの最後の部分を以下のように編集して，Autowareを起動してすぐにシミュレーションが始まらないようにするとうまくいくかもしれません．
（launchタグ内をtimerタグで囲ったのみです）

<timer period="60.0">
      <include file="$(find-pkg-share self_driving_controller)/launch/self_driving_controller.launch.xml" />
</timer>

**Comment by norikenpi** [comment]
質問なのですが，

> 同じコンテナで3回ほどシミュレーションをやり直すとなくなり, 

というのは，シミュレーションが終了した後，AutowareとAWSIMのウィンドウを閉じて，それぞれ使っていたコンテナ内で`bash run.sh`や `/aichallenge/AWSIM/AWSIM.x86_64`をするということでしょうか？

**Comment by makotoyoshigoe** [comment]
@norikenpi 様
対策法の提示ありがとうございます.  試し次第こちらに結果を報告します. 

質問への返答ですが, 記述頂いた内容で合っております.

**Comment by Reee009876** [comment]
お世話になっております。
ご連絡が遅くなり、大変申し訳ありません。

現在、こちら確認中になります。
そのため、[norikenpi](https://github.com/norikenpi)さまからご提案いただいている方法のご確認をお願いしたいです。

**Comment by makotoyoshigoe** [comment]
@Reee009876 様
返答いただきありがとうございます. 

> [norikenpi](https://github.com/norikenpi)さまからご提案いただいている方法のご確認をお願いしたいです。

承知しました. 今日中に確認を行い, こちらに報告いたします.

**Comment by makotoyoshigoe** [comment]
[norikenpi](https://github.com/norikenpi)さまからご提案いただいた方法を試したため報告します. aichallenge_subimit.launch.xmlの最後の部分を
```
<timer period="60.0">
     <include file="$(find-pkg-share self_driving_controller)/launch/self_driving_controller.launch.xml" />
</timer>
```
に変更してみたところ, 1つ目のダンボールは回避できたのですが, 2つ目のダンボールは回避できませんでした. そこで, 以下のように ```period```を```150.0```に変更して更にシミュレーションの開始を遅くしてみたところ, 2つ目以降のダンボールも回避できるようになりました. 

```
<timer period="150.0">
      <include file="$(find-pkg-share self_driving_controller)/launch/self_driving_controller.launch.xml" />
</timer>
```

この状態で2回オンライン環境に提出をしてみたところ, 2回ともローカル環境でうまく動いたときと同じスコアが出ました.

**Comment by Reee009876** [comment]
@makotoyoshigoeさま

ご確認いただきありがとうございます。
本件の詳細を確認いたします。

**Comment by makotoyoshigoe** [comment]
@Reee009876 様
承知しました.

こちら側で発生していた問題は解決したため, issueを閉じます. @norikenpi 様
解決方法を提示していただきありがとうございました.

**Comment by taikitanaka3** [comment]
Slackで連絡した内容をこちらにも転記させていただきます


Autowareでの物体認識がうまく機能していない、または[安定しない](https://aichallenge2023-integ.slack.com/archives/C05CJ9BJ96Y/p1691144998677179?thread_ts=1690966523.148849&cid=C05CJ9BJ96Y)とのフィードバックがありました。この問題を調査した結果、最新版に変更を加えることとしました。
影響を及ぼしている原因としてはいくつか考えられ、以下の点が挙げられます。（Autoware Miniを使用している方々はcenter pointを活用していないため、この問題の影響は受けません。）
Autowareを初めて起動する際、lidar_centerpointというノードがTensorRTの最適化を行い、/autoware/install/lidar_centerpoint/share/lidar_centerpoint/dataディレクトリに２つのengineファイルが生成されます。Dockerの環境下では、docker commitを行わない限り、変更したファイルが保存されません。その結果、Dockerを次回起動する際には、同じ処理を再度行う必要があり、約1分の待機時間が発生します。この問題を解決するために、.engineファイルをDockerに直接追加する方法も考慮しましたが、個々のGPU環境に応じて生成される.engineファイルが異なるため、都度生成が必要と判断しました。
ローカル環境での対応方法:
以下のコマンドを用いることで、ノードを個別に起動し、.engineファイルを生成することができます。
ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint_tiny
ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint 
また、生成された.engineファイルをdocker commitすることで、Dockerを次回起動する際の問題を回避する方法も考えられます。
オンラインの採点環境での対応:
上記の問題への対策として、.engineファイルをオンラインのAWS環境で生成し、それをdocker commitすることで問題を解決する予定です。
Center pointのconfigファイルが適切に設定されておらず、結果として検出精度が低下していました。このconfigファイルはAutoware launchから外部化されておらず、今回のコンペティションで簡単に変更できない形式となっていました。そのため、より安定したcenter point tinyを利用するように変更しました。
最新のブランチにおいては、Autowareのデフォルト設定でcenter_point_tinyが使用されるようになっています。この変更は大きくありませんので、必ずしも最新の情報をpullする必要はありませんが、perception launchに関しては、以下のように変更することを推奨します。
<arg name="centerpoint_model_name" default="centerpoint_tiny">
https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/pull/42
ーーーvia gpt
There were reports that object recognition with Autoware is not working well and is unstable. After investigating, changes were made to the latest version.
There were several causes, and the following seemed to have an influence. (Those using Autoware Mini are not affected as they don't use center point).
Upon the initial start of Autoware, the node named "lidar_centerpoint" runs optimization with TensorRT, and two engine files are generated in /autoware/install/lidar_centerpoint/share/lidar_centerpoint/data. In Docker, unless you commit with docker commit, even if a file changes, it won't be saved. Thus, there was a need to wait for about a minute again upon the next Docker start. We also considered adding the .engine file to Docker, but since the .engine file produced varies by the individual's GPU environment, it needed to be generated every time.
What can be done in a local environment:
You can generate the .engine file by launching the node individually with the following commands:
ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint_tiny
ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint 
Also, by committing the generated .engine file in Docker, you can avoid the same issue the next time you start Docker.
Actions to be taken in the online scoring environment:
To address the above issue, we plan to create the .engine file in the online AWS environment and address it by committing in Docker.
The config file for the center point was not set as intended, resulting in reduced detection accuracy. The configuration for center point was not externalized in the autoware launch and was included in files that could not be easily changed for this competition. We changed to the more stable center point tiny in the following PR.
In the latest branch, Autoware default now uses center point tiny. There aren't many changes, so you don't necessarily have to pull, but we recommend changing the perception launch as follows:
<arg name="centerpoint_model_name" default="centerpoint_tiny" 
https://github.com/AutomotiveAIChallenge/aichallenge2023-sim/pull/42 （
